version: '3.7'

services:

  db:
    container_name: db
    image: postgres:13.0
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    networks:
      - test_backend
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.26
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    ports:
      - 8000:8000
    networks:
      - test_backend
    restart: always
    depends_on:
      - db

  web:
    container_name: web
    build:
      context: ./$APP_BASE_DIR
      args:
        APP_BASE_DIR: $APP_BASE_DIR
    command: python manage.py runserver $WEBAPP_HOST:$WEBAPP_PORT
    env_file:
      - .env
    expose:
      - $WEBAPP_PORT
    networks:
      - test_backend
    restart: always
    depends_on:
      - db

networks:
  test_backend:
